### PR TITLE
The tail of the OS that didn't bark in the night

### PR DESCRIPTION
**Pull request by swfiua**
I am just starting writing some docs around the selector_select fun and games.

The stack traces have been annoying me and I really don't like catching exceptions.  I mean, what are you going to do with them.

But if the exception is OSError ... then I probably don't want to drop them all the time.

Anyway, I'll finish the story and then we can write some code to fix this up a bit.

more to come...

### CODE REVIEW

**Comment by dabeaz** [comment]
Yes.  Keep writing!  I want to learn.

**Comment by swfiua** [comment]
I just added some more.

I'm going to fix the code to include this *selector patience* idea.

**Comment by swfiua** [comment]
I haven't tested the latest fix on windows.  

There is some irony here, the next couple of weeks I'm probably not going to be using operating systems with weird selectors, but I will probably get a chance to try it on Monday.

**Comment by swfiua** [comment]
This is still a work in progress.

Some more changes to the selector exception handling.

I've added a piece on event loops, my thoughts on the tkinter issue.

Also discovered today that examples/prodcons.py on Windows raises three OSError's from the selector before it settles down.  Guessing there are two curio.run's and one of them is getting to the selector really early.

So for now, I would be patient with the SELECT_PATIENCE for now.

May add a piece on platforms: what works where, what's weird.

**Comment by dabeaz** [comment]
A question: should I leave all of this in a separate branch for now or should I pull it into master?   (Just looking a the "work in progress" comment above).

**Comment by swfiua** [comment]
Yes, leave it here for now.

I should probably create a branch at my end, maybe the 'patience' branch.

It might be good to have the docs in master, so I will then tidy the code for this pull request to be just the doc fixes.

**Comment by swfiua** [comment]
ps travis seems to be failing to get off the ground testing this branch.

**Comment by swfiua** [comment]
This is a docs only change now.

Three pieces.

One on the selectors, one on event loops and a piece on platfrom quirks and quarks.

The event loop piece is me trying to understand this thread https://github.com/dabeaz/curio/issues/111 and trying to explain what I am trying to do with the UI event loops.

All very much work in progress.

**Comment by dabeaz** [comment]
Closing (out of date).

**Pull request closed without merging**
