### PR TITLE
Add contextvar support.

### PR DESCRIPTION
**Pull request by Fuyukai**
Should work as expected on <3.7.

### CODE REVIEW

**Comment by imrn** [comment]
Does it have anything to do with maintaining current_taak?

**Comment by Fuyukai** [comment]
I personally think that they should be enabled and supported always, as it means there's no extra requirement for an app to use them other than use 3.7 or depend on contextvars for <3.6, instead of having to turn them on yourself (also can interact with libraries weirdly).

**Comment by dabeaz** [comment]
Ok, I'm sold!

**Comment by dabeaz** [comment]
I had to revert this pull request since it broke some stuff with async threads.  I'm going to revisit this, but the implementation will be different.

**Pull request merged**
