### PR TITLE
Use poll() instead of select() in writeable()

### PR DESCRIPTION
**Pull request by giampaolo**
...in order to avoid crashing if `fd > 1024`.

### CODE REVIEW

**Comment by giampaolo** [comment]
Also references https://github.com/dabeaz/curio/commit/7f7a680fa815fe12d83eab6efc2e1813a93b1008 and https://github.com/dabeaz/curio/issues/83.

**Comment by njsmith** [comment]
So the fallback here continues to crash if the `fd` is too large and `PollSelector` isn't available (I think this might happen on Windows?). Since this is just an optimization in the first place, maybe a better fallback would be to go directly to `_write_wait`? Or possibly even remove the optimization entirely, I guess. IIRC I suggested it in the first place but I don't think it's very important :-)

**Comment by giampaolo** [comment]
Right, `_write_wait()` is probably a better fallback than select(). =)
To be honest now that I look at this I don't understand the rationale behind `writeable`. Some questions:

- I'm probably missing something but given the buffer issue described in #83, shouldn't this (checking if fd is writeable) be done in all `send*` methods *before* the actual `socket.send*` call?
- I noticed `writeable()` is not documented and not used  anywhere except in a unit test. What's the use case of `writeable()` from a user standpoint?

**Comment by njsmith** [comment]
Have you read through #83? Both of those are explained downthread (though I know there's a lot of text there...)

**Comment by njsmith** [comment]
https://github.com/dabeaz/curio/issues/83#issuecomment-254103790 in particular might be relevant, but probably it needs context to make sense...

**Comment by dabeaz** [comment]
Looking at this, I'm thinking of going straight to _write_wait() as well.  Really, the point of the writeable() method was to provide a way to force I/O polling instead of eagerly trying to send if that's what you really needed to do.    It's probably fine to enter the kernel for that.

**Comment by giampaolo** [comment]
Done.

**Comment by JordanP** [comment]
I am following closely the git history of Curio. This PR was a bit messy. Please squash your changes before opening a PR, especially when your intermediary commits are not really meaningful. Thanks.

**Comment by giampaolo** [comment]
Yeah it was a bit messy indeed. Sorry about that.

**Pull request merged**
